# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.box = "ubuntu/focal64"
    master.vm.box_check_update = false
    master.vm.network "public_network", ip: "192.168.1.62"
    master.vm.synced_folder "src/", "/home/vagrant/src"
    master.vm.provision "shell", path: "provisionMaster.sh"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "node-1" do |node1|
    node1.vm.hostname = "node-1"
    node1.vm.box = "ubuntu/focal64"
    node1.vm.network "public_network", ip: "192.168.1.63"
    node1.vm.synced_folder "src/", "/home/vagrant/src"
    node1.vm.provision "shell", path: "provisionWorker.sh"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
